name: Workflow
on:
  push:
    branches:
      - feat

jobs:
# --------------------------------- BUILD ---------------------------------
  BUILD:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Instalar dependencias (si no están instaladas)
        run: npm install

      - name: Compilar y empaquetar
        run:  npm run build

      - name: Upload build output
        uses: actions/upload-artifact@master
        with:
          name: build-artifact
          path: ${{ github.workspace }}/.next
          include-hidden-files: true
# --------------------------------- SAST ---------------------------------
  SAST:
      needs: BUILD
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Download build artifact
          uses: actions/download-artifact@master
          with:
            name: build-artifact
            path: ${{ github.workspace }}/.next
            include-hidden-files: true

        - name: Validando existencia del proyecto en sonar
          run:  |
              set +e
              curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=laboratorio-final-2' -d 'project=laboratorio-final-2' -d 'organization=test-laboratorio' -d 'visibility=public'
              if [ $? -ne 0 ]; then
                echo "Proyecto ya existe en Sonarcloud"
                echo "::set-output name=proyectoExiste::1"
              else
                echo "Proyecto laboratorio-final creado exitosamente en Sonarcloud"
              
                echo "Se establece rama main feat como rama por defecto"
                curl -X POST -u "${{ secrets.SONAR_TOKEN }}:" 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main' -d 'project=laboratorio-final-2'
              fi
              set -e

        - name: Ejecutar análisis SonarCloud
          run: |
            npx sonarqube-scanner \
              -Dsonar.projectKey=laboratorio-final-2\
              -Dsonar.organization=test-laboratorio\
              -Dsonar.sources=./ \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
              -Dsonar.branch.name=main

        - name: Validando resultado de SonarCloud
          run: |
            projectKey="laboratorio-final-2"
            branchName="main"
        
            issueCount=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
              "https://sonarcloud.io/api/issues/search?componentKeys=${projectKey}&branch=${branchName}&types=VULNERABILITY&severities=BLOCKER,CRITICAL,MAJOR" \
              | jq '.total')

            echo "Vulnerabilidades críticas/altas/medias encontradas: $issueCount"

            if [ "$issueCount" -gt 0 ]; then
              echo "Se encontraron vulnerabilidades críticas, altas o medias. Deteniendo el pipeline..."
              exit 1
            else
              echo "No se encontraron vulnerabilidades críticas, altas ni medias. Continuando..."
            fi
  # --------------------------------- SCA ---------------------------------

  SCA:
    needs: BUILD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@master
        with:
          name: build-artifact
          path: ${{ github.workspace }}/.next
          include-hidden-files: true

      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@1.1.0
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: '${{ github.event.repository.name }}'
          path: '.'
          format: 'ALL'
          out: 'reports'
          args: >
            --failOnCVSS 7
            --enableRetired

      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@master
        with:
          name: dependecy-check-report
          path: ${{ github.workspace }}/reports

      - name: Validar resultado Dependency Check
        run: |
          report="reports/dependency-check-report.json"

          if [ ! -f "$report" ]; then
            echo "No se encontró el reporte de Dependency Check. Falla el análisis SCA."
            exit 1
          fi

          # Modificado para usar los valores correctos de severidad
          critical=$(jq '[.dependencies[].vulnerabilities[]? | select(.severity == "high")] | length' "$report")
          high=$(jq '[.dependencies[].vulnerabilities[]? | select(.severity == "high")] | length' "$report")
          medium=$(jq '[.dependencies[].vulnerabilities[]? | select(.severity == "moderate")] | length' "$report")

          echo "Vulnerabilidades críticas/altas: $critical"
          echo "Vulnerabilidades medias: $medium"

          if [ "$critical" -gt 0 ] || [ "$high" -gt 0 ] || [ "$medium" -gt 0 ]; then
            echo "Se encontraron vulnerabilidades Críticas, Altas o Medias en dependencias. Deteniendo el pipeline..."
            exit 1
          else
            echo "No se encontraron vulnerabilidades críticas, altas ni medias. Continuando..."
          fi
# --------------------------------- Docker Build ---------------------------------

  DockerBuild:
    needs: BUILD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@master
        with:
          name: build-artifact
          path: ${{ github.workspace }}/.next
          include-hidden-files: true

      - name: Build Docker Image
        run: |
          docker build --tag cesarrhf/laboratorio-final-2:latest .

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
         docker push cesarrhf/laboratorio-final-2:latest
# --------------------------------- Image Security ---------------------------------

  ImageSecurity:
    needs: DockerBuild
    runs-on: ubuntu-latest
    steps:

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Pull
        run: |
          docker pull cesarrhf/laboratorio-final-2:latest

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: cesarrhf/laboratorio-final-2:latest
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH,MEDIUM'
# --------------------------------- DAST ---------------------------------

  DAST:
    needs: DockerBuild
    runs-on: self-hosted
    steps:
      - name: Crear red Docker
        run: |
          if (docker network ls --filter name=zap-net -q) {
            docker network rm zap-net
          }
          docker network create zap-net

      - name: Limpiar contenedores antiguos
        run: |
         # docker rm -f $(docker ps -q --filter "ancestor=cesarrhf/laboratorio-final-2:latest") 2>$null

      - name: Desplegar aplicación
        run: |
          docker run --network zap-net -p 3000:3000 -d cesarrhf/laboratorio-final-2:latest

      - name: Esperar que la aplicación esté lista
        run: |
          sleep 30 

      - name: Escaneo con OWASP ZAP
        run: |
          docker run --rm --network zap-net -v C:/Users/cesar/actions-runner/_work/laboratorio-final/laboratorio-final:/zap/wrk/:rw ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t http://localhost:3000/ -J report_json.json -w report_md.md -r report_html.html -I
# --------------------------------- DEPLOY ---------------------------------