name: Workflow
on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop, feature/* ]

jobs:
# --------------------------------- BUILD ---------------------------------
  BUILD:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Instalar dependencias (si no están instaladas)
        run: npm install

      - name: Compilar y empaquetar
        run: |
          npm run build

      - name: Upload build output
        uses: actions/upload-artifact@master
        with:
          name: build-artifact
          path: ${{ github.workspace }}/.next
          include-hidden-files: true
# --------------------------------- SAST ---------------------------------
